# Website setup
title: Brandon's Website
description: >-
  Hi. My name is Brandon. This is my website.

# Contact Info
email: brandon.e.feder@gmai.com
baseurl : /
url: https://brandonfeder.com

# Build settings
theme: minima
markdown: kramdown
highlighter: rouge
    
# Collections
collections:
  projects:
    output: true